---
- name: awx jira create
  hosts: localhost
  tasks:
    - name: Create an issue
      community.general.jira:
        uri: https://bttcloud.atlassian.net
        username: karolis.zivulskas@bttcloud.com
        password: ATATT3xFfGF0NWSB-n_KuMAxKRocy4Hi5BV4Ibux_adT0TZJBp1MRPWd7G7W2U42oEQt9r7L2IYZ9WFDIq02U4WbsoiMs7xkhH2ShPWAQYmXg1UnmVCFMk1liEdeGaHTPl8omH8PfWYSlTs5XWbQ_BfQLZV6UUAztc2YvJYZon9GR81WTxZfwbs=0C65845F
        project: BRAVO
        operation: create
        summary: Packages update maintenance for LTAdvokatura
        description: sudo yum update -y
        issuetype: Maintenance
      args:
        fields:
          "customfield_10001":
            "name": "Bravo Team"
      register: issue
- name: debug
  hosts: ec2-18-198-25-175.eu-central-1.compute.amazonaws.com
  tasks:
    - name: Print some debug information 
      vars: 
        msg: |
           Ansible Distribution: {{ ansible_distribution }}
           Ansible Dist version: {{ ansible_distribution_version }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
- name: awx jira close
  hosts: localhost
  tasks:
    - name: Print the generated password
      debug:
        msg: "issue key is >>>  {{ issue.meta.key }}"
    - name: Resolve the issue
      community.general.jira:
        uri: https://bttcloud.atlassian.net
        username: karolis.zivulskas@bttcloud.com
        password: ATATT3xFfGF0NWSB-n_KuMAxKRocy4Hi5BV4Ibux_adT0TZJBp1MRPWd7G7W2U42oEQt9r7L2IYZ9WFDIq02U4WbsoiMs7xkhH2ShPWAQYmXg1UnmVCFMk1liEdeGaHTPl8omH8PfWYSlTs5XWbQ_BfQLZV6UUAztc2YvJYZon9GR81WTxZfwbs=0C65845F
        issue: "{{ issue.meta.key }}"
        project: BRAVO
        operation: transition
        status: Completed
#        fields:
#           resolution:
#             name: Done
# - name: Resolve the issue
#       community.general.jira:
#         uri: https://bttcloud.atlassian.net
#         username: karolis.zivulskas@bttcloud.com
#         password: ATATT3xFfGF0NWSB-n_KuMAxKRocy4Hi5BV4Ibux_adT0TZJBp1MRPWd7G7W2U42oEQt9r7L2IYZ9WFDIq02U4WbsoiMs7xkhH2ShPWAQYmXg1UnmVCFMk1liEdeGaHTPl8omH8PfWYSlTs5XWbQ_BfQLZV6UUAztc2YvJYZon9GR81WTxZfwbs=0C65845F
#         issue: '{{ issue.meta.key }}'
#         operation: transition
#         status: Resolve Issue
# #        account_id: 112233445566778899aabbcc
#         fields:
#           resolution:
#             name: Done
#           description: Task is done
  # - name: update
  #   shell: sudo yum update -y
  #   shell: sudo mkdir testing 
  #   shell: cd testing
    # - name: Get an issue
    #   community.general.jira:
    #     uri: https://bttcloud.atlassian.net
    #     username: karolis.zivulskas@bttcloud.com
    #     password: ATATT3xFfGF0NWSB-n_KuMAxKRocy4Hi5BV4Ibux_adT0TZJBp1MRPWd7G7W2U42oEQt9r7L2IYZ9WFDIq02U4WbsoiMs7xkhH2ShPWAQYmXg1UnmVCFMk1liEdeGaHTPl8omH8PfWYSlTs5XWbQ_BfQLZV6UUAztc2YvJYZon9GR81WTxZfwbs=0C65845F
    #     project: BRAVO
    #     operation: fetch
    #     issue: BRAVO-72
    #   register: issue
  # - name: Create an issue
  #   community.general.jira:
  #     uri: https://bttcloud.atlassian.net
  #     username: karolis.zivulskas@bttcloud.com
  #     password: ATATT3xFfGF0NWSB-n_KuMAxKRocy4Hi5BV4Ibux_adT0TZJBp1MRPWd7G7W2U42oEQt9r7L2IYZ9WFDIq02U4WbsoiMs7xkhH2ShPWAQYmXg1UnmVCFMk1liEdeGaHTPl8omH8PfWYSlTs5XWbQ_BfQLZV6UUAztc2YvJYZon9GR81WTxZfwbs=0C65845F
  #     project: BRAVO
  #     operation: create
  #     summary: Creating issue with awx
  #     description: For testing purposes
  #     assignee: 6406e9174d5e4b44e233ca2f
  #     issuetype: Maintenance
  #   register: issue
