---
- name: PowerShell Getting Started First Playbook
#  connection: ansible.windows.win_powershell
  gather_facts: false
  hosts: ec2-52-203-153-149.compute-1.amazonaws.com
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          New-Item C:\Users\Administrator\Desktop\testFILE.txt
