---
- name: awx jira
  hosts: localhost
  tasks:
    - name: Get an issue
      community.general.jira:
        uri: https://bttcloud.atlassian.net
        username: karolis.zivulskas@bttcloud.com
        password: ATATT3xFfGF0NWSB-n_KuMAxKRocy4Hi5BV4Ibux_adT0TZJBp1MRPWd7G7W2U42oEQt9r7L2IYZ9WFDIq02U4WbsoiMs7xkhH2ShPWAQYmXg1UnmVCFMk1liEdeGaHTPl8omH8PfWYSlTs5XWbQ_BfQLZV6UUAztc2YvJYZon9GR81WTxZfwbs=0C65845F
        project: ADVOKAT
        operation: fetch
        issue: ADVOKAT-25
      register: issue
- name: PowerShell Getting Started First Playbook
  connection: ansible.windows.win_powershell
  gather_facts: false
  hosts: all
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        error_action: stop
        script: echo "Hello World"
  # - name: Create an issue
  #   community.general.jira:
  #     uri: https://bttcloud.atlassian.net
  #     username: karolis.zivulskas@bttcloud.com
  #     password: ATATT3xFfGF0NWSB-n_KuMAxKRocy4Hi5BV4Ibux_adT0TZJBp1MRPWd7G7W2U42oEQt9r7L2IYZ9WFDIq02U4WbsoiMs7xkhH2ShPWAQYmXg1UnmVCFMk1liEdeGaHTPl8omH8PfWYSlTs5XWbQ_BfQLZV6UUAztc2YvJYZon9GR81WTxZfwbs=0C65845F
  #     project: BRAVO
  #     operation: create
  #     summary: Creating issue with awx
  #     description: For testing purposes
  #     assignee: 6406e9174d5e4b44e233ca2f
  #     issuetype: Maintenance
  #   register: issue
    # - name: Search for an issue
    #   community.general.jira:
    #     uri: https://bttcloud.atlassian.net
    #     username: karolis.zivulskas@bttcloud.com
    #     password: ATATT3xFfGF0NWSB-n_KuMAxKRocy4Hi5BV4Ibux_adT0TZJBp1MRPWd7G7W2U42oEQt9r7L2IYZ9WFDIq02U4WbsoiMs7xkhH2ShPWAQYmXg1UnmVCFMk1liEdeGaHTPl8omH8PfWYSlTs5XWbQ_BfQLZV6UUAztc2YvJYZon9GR81WTxZfwbs=0C65845F
    #     project: BRAVO
    #     operation: search
    #     maxresults: 10
    #     jql: project=BRAVO AND issuetype=maintenance
    #   args:
    #     fields:
    #       lastViewed: null
    #   register: issue
